### ISSUE TITLE
Team 70-Terriers

### ISSUE THREAD

**Issue by RamseyNjire** [kbjude/apple#2]

**Comment by RamseyNjire** [comment]
Have the Nav and footer outside of the main and everything else inside the main.

**Comment by s0kil** [comment]
The main body should be aligned vertically.
![Screenshot from 2020-01-09 09-34-56](https://user-images.githubusercontent.com/24403355/72076528-a666fc00-32c3-11ea-83ce-7e8a87cf51f6.png)

**Comment by moinkhanif** [comment]
Hey Jude, great work building the website! 👍

- You could give a max-width to the entire content and center it to improve its look on larger screens.
- You could give the background image to the internal div instead of the main tag.

optional: You could use the pseudo-class ":focus-within" to expand the search bar on focus.

Happy coding!

**Comment by kbjude** [comment]
Resolved
